### ISSUE TITLE
Font Color

### ISSUE THREAD

**Issue by dclechok** [vonbearshark/react-donut-chart#34]
Installed via npm i react-donut-chart, and for some reason I can modify most attributes of the font (including size, font-family, etc) from a parent element but I can't manage to give it a new color other than black. Is there someway I can change the font color easily? Thanks.

**Comment by vonbearshark** [comment]
This library uses SVGs, even for the `text` elements, which are a little different in that you provide coloring with the `fill` prop (instead of the `color` prop). So something like

```
.donutchart text {
  fill: red;
}
```

Would color all text as red, for example.

(I'm going to close this issue because I don't think it's related to the library, but we can still keep talking, and I'll open it back up if there's a fix needed.)

**Comment by dclechok** [comment]
Ahh I see thank you very much.
