### ISSUE TITLE
Important

### ISSUE THREAD

**Issue by adeludedperson** [vonbearshark/react-donut-chart#36]
Thanks sir for this awesome package. I made a tutorial on my own website about it can you see it https://bit.ly/3OnlDYg.

**Comment by huum4n** [comment]
I recently learned that if you put a "+" at the end of the link it redirects to a bitly website where it shows the original link.

[https://bit.ly/3OnlDYg](https://bit.ly/3OnlDYg) => [https://bit.ly/3OnlDYg+](https://bit.ly/3OnlDYg+)

![bitly](https://user-images.githubusercontent.com/49574179/206068751-304b87f9-e3db-4a3a-8f0c-6110083532e9.png)


Also I really like this component, I find it very useful.
 thanks for doing it.



I know no one asked: why I'm reading the issues?
I just want to be able to control where the arc starts (offset, startAngle) and maybe someone had already asked and there was an example around. :)

**Comment by vonbearshark** [comment]
> I just want to be able to control where the arc starts (offset, startAngle)

How do you mean? What are you trying to do?

**Comment by huum4n** [comment]
<img width="308" alt="chart" src="https://user-images.githubusercontent.com/49574179/209857189-9f25e340-851c-46f9-a858-78ac0f822f45.png">

the chart starts at the green line but I want to make the chart start at the red line

**Comment by vonbearshark** [comment]
My general thinking with this library is that you want to use the CSS styling as much as possible (instead of extending the library itself).

In this case, I think you want to do some kind of CSS `transform` on the `donutchart-arcs` class, [likely `rotate` combined with `transformX`/`transformY`](https://developer.mozilla.org/en-US/docs/Web/CSS/transform-function/rotate#combining_rotation_with_another_transformation), like `transform: translateX(Xpx) translateY(Ypx) rotate(Zdeg);`

**Comment by huum4n** [comment]
thanks, it works!
