### ISSUE TITLE
Cannot use import statement outside a module when using nextjs 13

### ISSUE THREAD

**Issue by phongpt156** [vonbearshark/react-donut-chart#39]
I got the following error message when using on nextjs project: Cannot use import statement outside a module

**Comment by vonbearshark** [comment]
How are you importing it exactly?

**Comment by phongpt156** [comment]
I just import it following the instruction: import DonutChart from 'react-donut-chart';

**Comment by matthewlewandowski93** [comment]
I had the same issue. I was able to resolve it by not rendering the graph on the server.
```const DonutChart = dynamic(() => import("react-donut-chart"), { ssr: false });```

**Comment by vonbearshark** [comment]
Thank you @matthewlewandowski93!

I was venturing into a similar rabbit hole. [As this comment suggests](https://github.com/asyncapi/asyncapi-react/issues/177#issuecomment-729823940), this problem is not specific to this library and next seems to struggle with SSR'ing browser-y things. In this case, though, we shouldn't need the browser, and SSR should work AFAIK. Later I see

>  [these] packages have only esm module in npm and NextJS needs cjs to render component in SSG

I can imagine that this issue is all some kind of build output issue on my end. That is actually where all of my maintenance time on this lib has gone--into building and deploying formats. It is pretty frustrating to keep up with. Given that this is exclusive to Next SSR, and there's a dynamic import workaround, I am going to close this issue.  But I am open to suggestions if they are straightforward
